### ISSUE TITLE
Run Passenger as non-root user

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#100]

**Comment by acozine** [comment]
Passenger overall runs as root but it does run the goldenseal app as the deploy user. However, the usual `ps aux` command didn't confirm this fact.  To confirm:
1. Set the instance directory for passenger (in /etc/httpd/conf.d/passenger.conf):
`PassengerInstanceRegistryDir /opt/goldenseal/shared/tmp/passenger`
2. Set the relevant environment variable for the root user:
`sudo export PASSENGER_INSTANCE_REGISTRY_DIR=/opt/goldenseal/shared/tmp/passenger/`
3. Get the PID for the passenger application with `sudo passenger-status`:

```
Version : 5.0.10
Date    : 2015-09-03 14:26:28 +0000
Instance: fe2oXFBk (Apache/2.4.6 (CentOS) Phusion_Passenger/5.0.10)

----------- General information -----------
Max pool size : 6
App groups    : 1
Processes     : 1
Requests in top-level queue : 0

----------- Application groups -----------
/opt/goldenseal/current:
  App root: /opt/goldenseal/current
  Requests in queue: 0
  * PID: 29259   Sessions: 0       Processed: 17      Uptime: 58m 24s
    CPU: 0%      Memory  : 149M    Last used: 1m 44s ago
```
1. Check the user with ps:

```
[alicia@ip-10-157-104-54 ~]$ ps -o pid,user,comm -p 29259
  PID USER     COMMAND
29259 deploy   ruby
```
