### ISSUE TITLE
Guest users cause constraint violation

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#103]
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_username"
DETAIL:  Key (username)=() already exists.
: INSERT INTO "users" ("groups_list_expires_at", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"):
  app/models/concerns/with_ldap_groups.rb:25:in `cached_groups'
  app/models/concerns/with_ldap_groups.rb:10:in`group

We installed a different version of devise guest users in alexandria.

**Comment by mark-dce** [comment]
Steps to reproduce - log out, then try to do a search.

**Comment by val99erie** [comment]
It looks like that devise-guest gem is meant to set random strings for the username:
username: "guest_V53UQwWmUC-827DMz_iA_1441729080_1"

But the User is being saved with a blank username.  (So, it works for the very first guest user, but not after that)

**Comment by jcoyne** [comment]
Yea, we've already fixed this in alexandria, we just need to copy the fix over.
