### ISSUE TITLE
Configure Imagemagick to correctly handle all JP2s

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#104]
There appears to be an issue with the version on ImageMagick we have installed on the server:

Server version: 6.7.8-9 
Current version: 6.9.2-0

**ON wustl.curationexperts.com**

```
[mark@ip-10-157-104-54 page-images]$ convert --version
Version: ImageMagick 6.7.8-9 2014-06-10 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP    

[mark@ip-10-157-104-54 page-images]$ convert letz_01_0001_unm.jp2 sample.tif
error: cannot decode code stream
convert: unable to decode image file `letz_01_0001_unm.jp2' @ error/jp2.c/ReadJP2Image/402.
convert: no images defined `sample.tif' @ error/convert.c/ConvertImageCommand/3046.
[mark@ip-10-157-104-54 page-images]$ ls sample.tif
ls: cannot access sample.tif: No such file or directory
[mark@ip-10-157-104-54 page-images]$ 
```

**ON Mark's local system**

```
MARKs-MB:page-images mark$ convert letz_01_0001_unm.jp2 sample.tif
MARKs-MB:page-images mark$ ls sample.tif
sample.tif
MARKs-MB:page-images mark$ convert --version
Version: ImageMagick 6.8.9-7 Q16 x86_64 2014-09-02 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules
Delegates: bzlib cairo fontconfig freetype jng jp2 jpeg lcms ltdl lzma png rsvg tiff xml zlib

MARKs-MB:page-images mark$ convert letz_01_0001_unm.jp2 sample.tif
MARKs-MB:page-images mark$ ls sample.tif
sample.tif
```

**Comment by mark-dce** [comment]
See Imagemagick install instructions at (note that the specific library versions in the wiki are out of date, but the overall process is probably still valid) https://github.com/curationexperts/mira/wiki/Updating-libtiff,-ImageMagick,-and-rmagick-on-Centos

**Comment by mark-dce** [comment]
FWIW - jpylizer (http://jpylyzer.openpreservation.org) reports the Lewald images as not being fully confermant to the JP2 standard.  But it also reports the same for the circuit court images...

OpenJP2 does seem to convert the Lewald images successfully

```
opj_decompress -i letz_01_0002_ttl.jp2 -o p2.tif
...
[INFO] Stream reached its end !
[INFO] Generated Outfile p2.tif
```

so it seems like an imagemagick compilation issue.

There is an issue with the color profile in the Legald images - it's not in the correct location in the file.  FITS reports it as missing, jpylizer reports is as being there, but in an invalid location within the file.

**Comment by acozine** [comment]
There's no version of ImageMagick that will do everything we need. 
Version 6.7.8 works with the code (which strips the file extensions)
Version 6.8.9 can convert the Lewald images but cannot recognize jp2 files without the file extension
Version 6.9.2 (current version) neither works with the code nor converts the Lewald images
For now, I've reverted to 6.7.8, which is the yum package version

**Comment by jcoyne** [comment]
Should be fixed in 6.9.2-1 https://github.com/ImageMagick/ImageMagick/issues/28

**Comment by acozine** [comment]
Installed ImageMagick 6.9.2-3 with openjp2 support. It successfully converts jp2 files in the circuit court collection, with or without the .jp2 file extension, but it does not convert files in the Fanny Lewald collection.

**Comment by mark-dce** [comment]
We can't  fix the convert issues, - but make sure we have a good ansible install for the version of Imagemagik+OpenJPEG we want and communicate to WUSTL.

**Comment by acozine** [comment]
Opened #156 for the ansible work. Closing this ticket.
