### ISSUE TITLE
Why does README require FITS 0.6.2

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#107]
The latest version listed at http://projects.iq.harvard.edu/fits/downloads is 0.8.6

There should at least be a callout to check [hydra-derivatives](https://github.com/projecthydra/hydra-derivatives) for the required version.

FWIW - my local system seems to run our apps fine and I have a homebrew installed version 0.8

**Comment by jcoyne** [comment]
Fits 0.8 emits metadata conforming to a different xml schema than 0.6. Hydra-derivatives reads/writes to an om data stream that matches the 0.6 schema. No one has wanted to commit resources to changing hydra derivatives, so we just list the version requirement.
