### ISSUE TITLE
Separate developer and production installation instructions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#108]
The current README.md appears to be focused on developer setup.  Document the corresponding steps for production setup in the README or a wiki page.

**Comment by mark-dce** [comment]
Per discussion, flag the readme as "Developer Setup Instructions" and give a pointer to Wiki production instructions somewhere (in the same repo OR the DCE ansible repo OR ...)

**Comment by acozine** [comment]
Dev instructions complete. Remaining work listed in #241
