### ISSUE TITLE
Javascript uploader file info disappears after files upload

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#109]
When you select multiple files for upload, sometimes the file information disappears, sometimes it stays on the screen.  See screenshot below:

<img width="1185" alt="wustl 109 - uploader file info dissapears" src="https://cloud.githubusercontent.com/assets/3064318/9751400/cb2e3b9c-5669-11e5-8f04-fa10229a4bd4.png">

**Comment by val99erie** [comment]
Note, per Mark:  This was 9 files uploaded at one time.  Some of the status lines disappeared while the other files were still uploading.

**Comment by mark-dce** [comment]
This behavior appears to only occur when the user has de-activated the window while a file upload completes (i.e. the user has switched to a different tab or window).    The behavior appears to be exclusive to Safari as well - Chrome and Firefox handle this case successfully.

**RESOLUTION**
In Safari, stay on the page if you want success updates to render successfully.  There is no impact either way on the actual back-end jobs and file attachments.
