### ISSUE TITLE
A-7: Browser based file upload

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#11]
From the SOW:

> Provide user-friendly browser based content upload for single and multiple files.  Metadata is applied to all files within a single upload. This functionality is largely an outcome of the base application development and is listed here as a checkpoint to measure project progress.

**Comment by val99erie** [comment]
Question:
Can this be on the edit page (after you have already created a work), similar to Digital Case?

**Comment by jcoyne** [comment]
This feature was added to absolute by: https://github.com/KelvinSmithLibrary/absolute/commit/ae0e0e7375abf846b448b170d76ae34244806623

**Comment by jcoyne** [comment]
Question:
If this is for batch ingest, how do we know which uploaded files are grouped together into works?  How does this fit in the UI?

**Comment by mark-dce** [comment]
I had thought Absolute/worthwhile also supported single file end-user self-deposit.  In any case, that's what this ticket is about: single user, single work, non-batch file upload - basically Sufia-style self deposit.

**Comment by val99erie** [comment]
@mark-dce The SOW specifies that it needs to support multi-file upload.

**Comment by mark-dce** [comment]
@val99erie - to clarify, The uploader needs to be able to create a single work and it's associated metadata.  A single work should be able to have zero or more (i.e. multiple) digital files attached to it.

**Comment by mark-dce** [comment]
@val99erie - based on what's there already in concern/#{type}/new, what we have is great and we just need to add the ability to add more than one file for upload.  Depending on which is easier, the lower limit could either be zero or one digital files attached to a work via the UI.

**Comment by mark-dce** [comment]
**ACCEPTANCE**
- [x] Test upload of each work type in A-6 for single files
- [x] Ensure additional files can be attached via edit view
