### ISSUE TITLE
Update curation concerns to use URI for "All Rights Reserved"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#110]
http://www.europeana.eu/portal/rights/rr-r.html
- [x]  update the generator at https://github.com/projecthydra-labs/curation_concerns/blob/a2bb10261e39b8912fd7f7df4018f73c40633577/curation_concerns-models/lib/generators/curation_concerns/models/templates/config/curation_concerns.rb#L18
- [ ] updated the local version at https://github.com/curationexperts/goldenseal/blob/master/config/initializers/curation_concerns.rb#L25

**Comment by jcoyne** [comment]
Pending merge of https://github.com/projecthydra-labs/curation_concerns/pull/318
