### ISSUE TITLE
Thumbnails on video/images

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#134]
If you make an Image or Video object and then attach an image or video respectively, the representative doesn't automatically get set, thus the work doesn't get a thumbnail until you click "edit" and then "Save"

**Comment by val99erie** [comment]
Also see #214, it seems we need to test the mime-type before setting the representative & thumbnail

**Comment by val99erie** [comment]
Waiting for PR 438 to be merged on curation_concerns.  Then I'll need to update the curation_concerns version in goldenseal's Gemfile before I can close the story.
