### ISSUE TITLE
Can't upload long video

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#137]
My browser hangs when I try to upload fma-2-78436-acc-20140424.full.mov

I've tried using the "choose file" option when creating a new video work and creating a work without attachments and using the Javascript uploader.  

We either need to 
Alternative 1) be able to upload these files, or 
Alternative 2) communicate to WUSTL how the files would need to be changed, or 
Alternative 3) provide messaging that files larger than a certain size need to be ingested from the command line on the server.

<img width="880" alt="wustl 137 - large file upload" src="https://cloud.githubusercontent.com/assets/3064318/9913005/1e4a32ca-5c70-11e5-9fc5-f48e39eab336.png">

**Comment by mark-dce** [comment]
Use the files in /opt/sample-data/Addonizio-Avila-Interviews for testing - we should be able to upload both of them

**Comment by jcoyne** [comment]
Possibly associated with this (in the apache error_log):

```
App 28334 stderr: [ 2015-09-16 16:50:26.3937 28359/0x000000028df7f0(Worker 1) utils.rb:85 ]: *** Exception Errno::ENOSPC in Rack application object (No space left on device @ io_write - /tmp/RackMultipart20150916-28359-1y1tp59.mov) (process 28359, thread 0x000000028df7f0(Worker 1)):
```

**Comment by acozine** [comment]
I added a 50GB drive mounted at /tmp. I copied the existing content over for continuity. We can re-test now.

**Comment by mark-dce** [comment]
Retested and derivatives are still not being created.  It looks like the characterize job failed - job_id: 9d309fc3-b5df-40e5-a957-d685dd2e1e88 - in resque-web

**Comment by acozine** [comment]
The derivatives error was:

```
java.lang.NoClassDefFoundError: org/apache/tika/mime/MimeTypeException</str><str name="trace">java.lang.RuntimeException: 
```

It was introduced with the upgrade to Solr 4.10.4. The tika jars were present and being loaded but the solr-cell jar was not. I moved the solr-cell jar out of lib/ and into lib/contrib/extraction/lib, and extraction started to work. Possibly we are not loading most of the jars in lib/ - extraction still worked when I removed most of the jar files that ship with Solr, leaving only:

```
[alicia@ip-10-157-104-54 lib]$ ls -la
total 2812
drwxr-xr-x 3 tomcat tomcat      85 Oct  1 15:50 .
drwxr-xr-x 5 tomcat tomcat      89 Oct  1 16:12 ..
drwxr-xr-x 4 tomcat tomcat      45 Oct  1 15:48 contrib
-rw-r--r-- 1 tomcat tomcat   17630 Oct  1 15:38 solr-analysis-extras-4.10.4.jar
-rw-r--r-- 1 tomcat tomcat 2855487 Oct  1 15:38 solr-core-4.10.4.jar
[alicia@ip-10-157-104-54 lib]$ ls -la contrib
total 0
drwxr-xr-x 4 tomcat tomcat 45 Oct  1 15:48 .
drwxr-xr-x 3 tomcat tomcat 85 Oct  1 15:50 ..
drwxr-xr-x 4 tomcat tomcat 51 Oct  1 15:38 analysis-extras
drwxr-xr-x 3 tomcat tomcat 33 Oct  1 15:38 extraction
```

The jars in the analysis-extras directory tree are unchanged from the vanilla solr 4.10.4 distribution. 

With this change, long videos upload and transcode correctly.
