### ISSUE TITLE
B-5: Base lease and embargo implementation

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#14]
Text from the SOW:

> Provide support for automatic lease termination and notification of embargo expiration. This functionality is largely an outcome of the base application development and is listed here as a checkpoint to measure project progress.

**Comment by val99erie** [comment]
Some questions:
- [x] Does wustl currently have any objects with lease/embargo data?
- [x] Should lease/embargo options be available to a self-deposit user?
- [x] If a self-deposit user can make an embargo, how would that embargo be lifted?  Would an admin be required to lift it?  Or do we need to build out non-admin embargo management UI?
- [x] Should lease/embargo options be available to an admin user?

**Comment by jcoyne** [comment]
There is no non-admin self-deposit in the current scope. But they want lease and embargo options available. They don't haven any current objects with lease and embargo but they plan to in the future.

**Comment by jcoyne** [comment]
- [x] Admin users should see a link to the embargo controller in curation_concerns
