### ISSUE TITLE
Don't prompt to apply leases/embargos to children if there are no files attached.

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#141]
When I set an embargo on a work, I should not be prompted whether I want to apply the embargo to files within the image if there are no files attached.

See http://wustl.curationexperts.com/concern/images/xd07gs724
The work has no files attached, but I get this message if I set or change the embargo:

<img width="1150" alt="wustl 141 - embargos applied to non-existent children" src="https://cloud.githubusercontent.com/assets/3064318/10167069/9127ef1e-668c-11e5-94f9-5f3a23c4c845.png">

**Comment by mark-dce** [comment]
Time-bound fix to 4 hours; if not, add to scoping for a future phase.

**Comment by mark-dce** [comment]
Look at #142 first, fixing it might make this story redundant depending on the specific way you choose to implement #142

**Comment by mark-dce** [comment]
This is still happening:

<img width="976" alt="wustl 141 - reopened - sample with no files attached" src="https://cloud.githubusercontent.com/assets/3064318/10809536/d604b22c-7db4-11e5-97a0-7306556bc717.png">

<img width="987" alt="wustl 141 - reopened - change access rights" src="https://cloud.githubusercontent.com/assets/3064318/10809535/d5d3bd0c-7db4-11e5-89e3-268de1a1346a.png">

<img width="984" alt="wustl 141 - reopened - prompt to update non-existent files" src="https://cloud.githubusercontent.com/assets/3064318/10809537/d60907e6-7db4-11e5-89b8-74d46d8296c0.png">

**Comment by jcoyne** [comment]
The first ticket was for leases and embargos only.  So this should be closed an a new ticket opened. Original ticket fixed by https://github.com/projecthydra-labs/curation_concerns/commit/d5464453225d5813a3dd4dee4aa6ccff18dfaf94  New ticket #224
