### ISSUE TITLE
Improve performance of embargo and lease pages

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#143]
**ISSUE**
The /embargoes  view takes a noticeably long time to load.  The leases view loads quickly (but there are no leases right now) so it seems like this might be a linear delay based on the number of embargo or leases in effect.  Because turbo links are enabled, it's difficult to tell whether the system is working or just hung.

**ACCEPTANCE**
- [x] Spend 2-4 hours diagnosing the underlying cause of the slowness
- [x] Identify 1 or more potential or partial fixes
- [x] Discuss as a team whether to implement any of the fixes or whether they need to be incorporated in a future SOW

**Comment by jcoyne** [comment]
It's hitting the Fedora API directly rather than pulling the data from Solr. Furthermore there is no limit to the number of records on the page, which means that time to create it is basically unbounded.

**Comment by mark-dce** [comment]
Make it so:  pull the data from Solr instead of Fedora

**Comment by jcoyne** [comment]
<img src="https://thabto.files.wordpress.com/2013/10/make-it-so-captain.jpg">
