### ISSUE TITLE
Lease/Embargo info shown on attached file view is incorrect

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#147]
**STEPS TO REPRODUCE**
1. Create a new work, attach a file, set an embargo on the work and the file
2. Go to manage embargo and deactivate the embargo on the work only, leave the embargo on the file.
3. Edit the work and apply a lease, do not apply the lease to attached files.
4. Edit the attached file and check the permissions.

**EXPECTED RESULT**
The attached file should still have the original embargo.
<img width="821" alt="wustl 146 - child embargo bug - step 1" src="https://cloud.githubusercontent.com/assets/3064318/10170257/aa2b8a4a-6699-11e5-9a2b-5b97f28b05a0.png">

**ACTUAL RESULT**
The attached file has a lease instead of the original embargo.
<img width="809" alt="wustl 146 - child embargo bug - step 4" src="https://cloud.githubusercontent.com/assets/3064318/10170259/b0057aca-6699-11e5-975e-736cdc5481df.png">

**Comment by jcoyne** [comment]
I was unable to duplicate this.

**Comment by jcoyne** [comment]
Hmm, I did duplicate it on the demo server.
