### ISSUE TITLE
Can't set access rights on collections

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#152]
**STEPS TO REPRODUCE**
1) Log in as any user
2) Add a new collection by clicking on the "+" icon in the header and clicking on "Add a Collection"
3) Give the collection a title and set the Access Rights to "Open Access"
4) Click the "Create Collection" button

_EXPECTED RESULTS_
The collection view page is displayed and the access rights show "Open Access"

_ACTUAL RESULTS_
The collection view page is displayed and the access right still show "Private", even if I refresh the page after some time.

_NOTE:_ I get the same behavior when I try to change the Access Rights on an existing collection.  I.E. whatever I set them to, once I click "Save Changes", the collection shows up as "Private"

**ACCEPTANCE**
- [ ] I can set the access rights to "Open Access" or "Institution Name" when I create a collection
- [ ] I can change access rights after the collection has been created

**Comment by jcoyne** [comment]
Due to `Unpermitted parameter: visibility`
