### ISSUE TITLE
Identify problematic jar file for MimeTypeException

### ISSUE THREAD

**Issue by acozine** [curationexperts/goldenseal#154]
See #137

If I install Solr 4.10.4 with all included jar files, characterization of video files fails with

```
java.lang.NoClassDefFoundError: org/apache/tika/mime/MimeTypeException</str><str name="trace">java.lang.RuntimeException: 
```

Spend up to 4 hours to identify which jar file causes the issue.

Justin created this command line test:

```
curl "http://localhost:8080/hydra/update/extract?extractOnly=true&extractFormat=text" -F "myfile=@/opt/goldenseal/current/spec/fixtures/dlxs/short-lew-dc.xml"
```

**Comment by acozine** [comment]
To fix this issue reliably, move solr-cell*.jar our of the main lib/ directory and into lib/contrib/extraction/lib. Other jar files can remain where they are/were.

**Comment by jcoyne** [comment]
That seems wrong. Solr-cell is a core piece of solr. It doesn't belong in contrib

**Comment by acozine** [comment]
I agree that it seems wrong. But it works. I’d appreciate a second set of eyes to figure out a fix that makes sense AND works.
