### ISSUE TITLE
Video player does not display playback controls on the work show page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#155]
**ISSUE**
For video works, the main show page does not seem to be displaying the player controls correctly.   Playback time, scrubber, volume and other controls are not displayed.   The controls display as expected in the generic file show view.

**SAMPLES**
See the work: http://wustl.curationexperts.com/concern/videos/w66343646
VS. the generic file:
http://wustl.curationexperts.com/concern/generic_files/5138jd87r

**SCREENSHOTS**
<img width="532" alt="wustl 155 - playback controls on works" src="https://cloud.githubusercontent.com/assets/3064318/10250595/554709d2-68f1-11e5-94f7-89156b52532b.png">

<img width="535" alt="wustl 155 - playback controls on genericfile" src="https://cloud.githubusercontent.com/assets/3064318/10250596/5549fd2c-68f1-11e5-94a0-9664b25bae9d.png">

**Comment by jcoyne** [comment]
Possibly because there is no TEI for this asset:    

```
GET http://wustl.curationexperts.com/concern/generic_files/5138jd87r.vtt
404
```

**Comment by mark-dce** [comment]
looks that way - see http://wustl.curationexperts.com/concern/videos/4f16c2806 which works fine (and has a transcript)

**Comment by acozine** [comment]
Fixed as of 10/7. Video works without TEI correctly display controls on the work show page. Thanks, Justin.
