### ISSUE TITLE
Media player (Audio/Video) on the show page for the work

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#16]
Part of SOW D-2:

> Implement a basic media player based on WU specific requirements

**Comment by jcoyne** [comment]
Assigning to Alicia for testing.

**Comment by acozine** [comment]
Test mp3 and wav audio objects, basic opensource video formats.

**Comment by jcoyne** [comment]
From SOW:

```
DCE will implement the core object types supported by Worthwhile: PDFs; Microsoft Office, OpenOffice, & LibreOffice Documents; Tiff & JPEG Images; MP3 & Wave Audio; and open source Video formats.
``
```

**Comment by val99erie** [comment]
If everything works, then SOW A-6 is completed

**Comment by acozine** [comment]
Audio and video both work. PDF error documented in https://github.com/projecthydra-labs/curation_concerns/issues/189. Closing, since this ticket is about media players and they are good to go.
