### ISSUE TITLE
Clean up DC collection import parser

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#161]

**Comment by val99erie** [comment]
Clean up old code for an importer that we aren't going to use, and all the supporting code.  See these commits:

https://github.com/curationexperts/goldenseal/commit/24ac5737bb8a91ec4cc04dd7246aff7dea911904
and
https://github.com/curationexperts/goldenseal/commit/d649c077434f6a91b8d5f25aa4e2caa707eb1d66
