### ISSUE TITLE
TEI Importer doesn't index all thumbnails correctly

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#163]
When I use the TEI importer to import one of the Fanny Lewald novels, not all page images are getting proper thumbnails:

Command for the import:

```
RAILS_ENV=production bundle exec script/import_text /opt/sample-data/fanny-lewald-TEI-textimage-DCE-changes open
```

Created this work: 
http://wustl.curationexperts.com/concern/texts/zc77sq08x

See the the following files in the "Files" list for examples:
letz_01_0001_unm.jp2
letz_01_0009_008.jp2
letz_01_0021_020.jp2

**Comment by jcoyne** [comment]
It's indexing the "Default" Image rather than the path to the thumbnail derivative.  Indexing may be happening out of order, or maybe not happening after creating a derivative.

**Comment by val99erie** [comment]
It looks like the thumbnails are getting properly created, and some of the solr documents properly have the thumbnail, but some of them have the default thumbnail.  My first guess is that there is a race condition between the actor that creates the files and the background job(s) that create the derivatives.

**Comment by val99erie** [comment]
Note that re-indexing the individual pages does fix the problem.

**Comment by jcoyne** [comment]
Fixed by https://github.com/projecthydra-labs/curation_concerns/commit/c71e0729cb07a6af3542ebd8fc7144f091d57596
