### ISSUE TITLE
E-2: Book reader

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#17]
Part of SOW E-2:

> Configure a book-reader like interface for WU TEI.

Tasks:
- [x] Gather requirements for the book viewer

Questions:
- [x] Is there an existing book reader that they are interested in using?

**Comment by val99erie** [comment]
We discussed it in today's meeting.  We want to copy the book viewer from Digital Case.

Tasks:
- [ ] Copy the book viewer from Digital Case
- [ ] They have some collections that have TEI, but no images, so we need to make sure that test case works

**Comment by acozine** [comment]
See https://github.com/KelvinSmithLibrary/absolute/issues/25

**Comment by jcoyne** [comment]
Move the TEI to the files container. Make a separate predicate to point at it.
