### ISSUE TITLE
Collections should not have an "Add to Collection" option in search results

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#174]
<img width="746" alt="wustl 174 - remove add to collection option for collections" src="https://cloud.githubusercontent.com/assets/3064318/10404641/a688094c-6e99-11e5-8219-dd358ff1b598.png">

**Comment by jcoyne** [comment]
Why? Worthwhile always supported nested personal collections. Is there some reason we want to revert that?

**Comment by mark-dce** [comment]
I didn't realize worthwhile/curation_concerns supported nested personal collections and thought this was just a UI oversight.
