### ISSUE TITLE
Product name is not correctly configured

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#175]
<img width="660" alt="wustl 175 - product name isn t correctly configured" src="https://cloud.githubusercontent.com/assets/3064318/10404732/26239a22-6e9a-11e5-94aa-11e1370366e4.png">

**Comment by jcoyne** [comment]
That is correctly configured. I just think we can't have HTML in the confirm dialogs.  we can fix in curation_concerns by doing: 

```
t('sufia.product_name', default: 'Product Name')
```

**Comment by mark-dce** [comment]
Right - I put the screenshot because I suspected there might be one or more of four issues going on:
1) the HTML is an issue
2) we don't have en.sufia.product_name defined in goldenseal
3) curation_concerns probably should probably have something like 'app.product_name' instead of 'sufi.product_name'
4) curation_concerns doesn't default properly as you show above

**Comment by jcoyne** [comment]
So, do we have a "product name" for this?  Shall we call it "goldenseal"?

**Comment by jcoyne** [comment]
https://github.com/projecthydra-labs/curation_concerns/pull/390
