### ISSUE TITLE
Video transcripts not displaying

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#179]
**EXAMPLES**
- http://wustl.curationexperts.com/concern/videos/dz010q06g
- http://wustl.curationexperts.com/concern/videos/k643b1186

**STEPS TO REPRODUCE**
(sample files in /opt/sample-data/americas_war_on_poverty)
1. Create a new video work without any files attached
2. Add the files _addonzio-lofi.mov_ and _add14885.01250.032-dce-cleaned.xml_ to the work
3. Let the derivative jobs complete...
4. Edit the work and select the representative video thumbnail and transcript file
5. View the work

_EXPECTED RESULT_
The video playback window displays next to a populated transcript window

_ACTUAL RESULT_
Only the video playback displays; there is no transcript.

**Comment by jcoyne** [comment]
The fix is to:

```
git mv app/views/curation_concerns/generic_files app/views/curation_concerns/file_sets
```
