### ISSUE TITLE
"Content License" not being saved on works

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#184]
**STEPS TO REPRODUCE**
## Create a new work, set the content license, and save the new work

<img width="825" alt="wustl 184 - create w-content license" src="https://cloud.githubusercontent.com/assets/3064318/10462646/6d92a32c-71a5-11e5-9db8-346e8760e3b2.png">
## View the newly created work and the content license doesn't show up...

<img width="830" alt="wustl 184 - show - no content license" src="https://cloud.githubusercontent.com/assets/3064318/10462664/7e7f3fc4-71a5-11e5-80db-3d40fc34db09.png">
## Edit the work and re-select a content license and re-save the work

<img width="810" alt="wustl 184 - update - re-select content license" src="https://cloud.githubusercontent.com/assets/3064318/10462674/90472f82-71a5-11e5-8582-a17c149a76f4.png">
## View the updated work, and content license is still blank, even though other updates were saved

<img width="827" alt="wustl 184 - show after update - still no content license" src="https://cloud.githubusercontent.com/assets/3064318/10462694/adfd64ce-71a5-11e5-9650-b96e90cd637d.png">

**Comment by jcoyne** [comment]
It _is_ being saved. It's just not displayed on the show page.
