### ISSUE TITLE
Some properties not being saved

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#193]
Fill in the form to create a new work.  When you save it, some of the attributes don't get saved.

A comment from Justin that might be related:
"We should look into this: Unpermitted parameters: editor, sponsor, funder, researcher, identifier, series, extent, note, description_standard, publication_place, date_issued"

**Comment by jcoyne** [comment]
If that is indeed the culprit, add terms to the *WorkForm rather than permitting attributes on the *Controller.
