### ISSUE TITLE
Provide a way to log importer output and display it on the console

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#194]
Either an an option to log output to a file in addition to displaying on the console 

OR

Help Mark figure out how to get `tee` to run successfully.

**Comment by val99erie** [comment]
Mark:  I think the tee command is creating a new process in ruby.  I don't have much more time to figure it out tonight, so I'll take a closer look at it tomorrow.

If you plan to work on it more tonight, here's a post that might be helpful.  The commenter mentions a "script" command that's available in bash.  I don't know if that will work for you or not.  I'll test it out tomorrow.

http://stackoverflow.com/questions/27852705/pipe-every-bash-output-to-file

If you want to play around with it, I created a test script on the sandbox:
/home/deploy/test_script.rb
