### ISSUE TITLE
I:  Implement on-campus restriction

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#20]
From the SOW:

> Default access levels are “Public”, “Intitution-only”, and “Private”.  DCE will implement the necessary enhancements to support additional levels of access granularity

Questions:
- [x] What access categories do you need?  Are the defaults enough?
- [x] What sorts of things need IP/location protection?  Is this just on-campus IPs?
- [x] How many IP ranges will there be?
- [x] Do we need to differentiate between "read" access and "discover" access?

**Comment by jcoyne** [comment]
I think we can just implement this as a visibility called "On Campus".

**Comment by jcoyne** [comment]
It sounds like we just need one group of IP blocks for "on campus" things.

**Comment by val99erie** [comment]
Based on discussion from today's meeting, we can ignore "read" vs "discover" for now.  There may be a future need for that, but we'll defer it until it's actually needed.

**Comment by acozine** [comment]
IP-restricted content includes ETDs, which are currently stored in BePress - branded for WUSTL as Open Scholarship.

**Comment by mark-dce** [comment]
- [ ] Add a "Campus Use Only" option to the Access Rights set of "Private", "Institution", "Open Access"
- [x] Pull in the IP-address restriction code from Alexandria-2
- [x] Don't commit their IP ranges to the repo, read from a config file instead
- [ ] Document where WUSTL should configure their IP ranges on production instances

**Comment by val99erie** [comment]
Question:  Where can we find the IP ranges that WUSTL considers to be on-campus?

**Comment by mark-dce** [comment]
We can't test with their ranges anyway, so let's just use ones that corresponds to our office:

75.149.149.05 - 75.149.149.15  #DCE Office NAT's to public IP 75.149.149.10
10.1.10.1 - 10.1.10.254  #DCE Office uses private network 10.1.10.0/24 - this range is un-routable, so should have any effect, but shows what having two ranges configured looks like.

And add your home IP if that's useful for testing too

**Comment by mark-dce** [comment]
WUSTL appears to own 128.252.48/24 if you want to use that.  Otherwise, we can shoot Mark S. an e-mail and ask.  I'm not sure whether they will want them stored in the repo.

**Comment by mark-dce** [comment]
- [x] WUSTL's real IP address range data should not be stored in a publicly accessible location - eg. ip address prefixes should be stored in a config file - save a sample in the repo, configure actual production data on the production server only (much like we treat passwords)
- [x] The check needs to treat subnets numerically, not lexically - i.e. matching subnet .1 should not match subnet .10 or .115 (See implementation note)
- [x] The check needs to be performant when there are a large number of subnets permitted - i.e. WUSTL has approximately 254-66 = 188 subnets the application will have to permit 'on-campus' access from

**IMPLEMENTATION DETAIL**
We might want to look at the rails IPAddr class to do the range checking (see http://ruby-doc.org/stdlib-1.9.3/libdoc/ipaddr/rdoc/IPAddr.html#method-i-include-3F), that might help solve distinguishing between 128.252.1.15 being in range and 128.252.11.5 being excluded (the alex code looks like both would match on '128.252.1' - at a minimum, we need to include the trailing period after the subnet prefix like this '128.252.1.'  The trailing period solution only work on masks that are divided on even 8-bit boundaries(/8 /16 /24), so it wouldn't work for a subnet like 172.43.96.0 / 18.

**Comment by jcoyne** [comment]
We still need a FileSetPresenter that overrides `PresentsAttributes#extract_dom_label_class_and_link_title` for the badge.
