### ISSUE TITLE
Don't attempt to retain order of pages on text works

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#202]
Treat pages as unordered PCDM files when attached to Text works to provide better ingest performance.

**Comment by mark-dce** [comment]
Re-evaluate need for this after #196 is done (Trey's performance changes to ordered member lists)

**Comment by mark-dce** [comment]
@jcoyne - so is it worth considering this in relation to #196, or should we just close it?

**Comment by jcoyne** [comment]
Just close this.

**Comment by jcoyne** [comment]
This would require too much work on curation_concerns. I think we have many of the performance issues addressed now. See #196
