### ISSUE TITLE
Improve edit view load time for long texts

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#203]
When I load an image work, the edit view takes under 2 seconds to load.

When I load a text with around hundreds of pages like http://wustl.curationexperts.com/concern/texts/1v53jx03v, the edit view takes nearly a minute

**Comment by mark-dce** [comment]
Let me know if I need to create new samples after the server rebuild.

**Comment by mark-dce** [comment]
Still appears to be happening - see http://wustl.curationexperts.com/concern/texts/xk81jk50j

**Comment by jcoyne** [comment]
I'm pretty sure this is the time to render the select a thumbnail widget.

**Comment by mark-dce** [comment]
We either need a much faster load time, or we need to disable turbo-links on the view.  Right now, you click the button and there's no way to tell that anything is happening for over a minute.
