### ISSUE TITLE
Add /tmp/uploads info to readme or wiki

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#206]
Add information to README or Wiki about periodically cleaning up /tmp.  See #199 for additional details.

**Comment by jcoyne** [comment]
it's not `/tmp/uploads` it's `/opt/goldenseal/shared/tmp/uploads`

**Comment by mark-dce** [comment]
Point taken :) - I meant #{Rails.root}/tmp/uploads
