### ISSUE TITLE
Document final component versions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#209]
Communicate final versions to WUSTL via e-mail or other means.

Versions as initially listed in the SOW:

> Target Operating Environment
> DCE will develop the system to function in the following target environment:
> OS and version  Red Hat (CentOS) 6.6 
> Ruby version    ruby 2.1.5 
> Fedora version  Fedora 4.1.1
> Java version    Java OpenJDK 1.7.0_75
> Java server Tomcat 7.0.59
> Solr version    Solr 4.10.3
> Database    MySQL 5.6.23
> Web server  Apache  2.2.15-39 
> App Server  Passenger 4.0.59 
> Alternate component versions may be supported based on discussion and mutual agreement between WU and DCE.

**Comment by acozine** [comment]
Final versions as of 11/3/15:
- CentOS 7.0
- Ruby 2.2.3
- Java (Sun Java) 1.8.0_51
- Tomcat 7.0.54-2.el7_1 (via yum)
- Fedora (fcrepo) 4.4.0
- Solr 4.10.4
- Postgresql 9.2.13-1.el7_1 (via yum)
- Apache (httpd) 2.4.6-31.el7.centos.1 (via yum)
- Passenger 5.0.10 (as a gem)
- FITS 0.8.4
- ImageMagick 6.9.2-5 with
  - libpng-1.6.18
  - openjpeg-2.1.0
  - tiff-4.0.5
