### ISSUE TITLE
J-2: Synchronized Audio/Video Transcript Playback

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#21]

**Comment by val99erie** [comment]
Investigate which tools would could use for this.  Take a look at these:

https://github.com/WGBH/openvault/blob/master/app/assets/javascripts/openvault/sync.js
https://github.com/afred/openvault-redux/blob/877feabc9828c036592c3bf5fc97d18a8df8c422/app/helpers/media_helper.rb#L8
https://github.com/WGBH/openvault/issues/634

**Comment by mark-dce** [comment]
Based on the sample TEI provided by WU, I think we're going to want to use the Tufts viewer model.  I.E. the have pretty large segments of text with relatively sparse time-code information, so we just want to display large chunks of text adjacent to the video playback window.

Sample Tufts video with transcript: http://dl.tufts.edu/catalog/tufts:MS165.002.001.00002

Code for display page: https://github.com/TuftsUniversity/tdl/blob/master/app/views/catalog/_show_tufts_videos.html.erb

Code for player: https://github.com/TuftsUniversity/tuftsification-hydra/blob/master/app/assets/javascripts/media_player/transcript_scroller.js

**Comment by acozine** [comment]
ACCEPTANCE:
I have:
1. a video or audio work and
2. an associated video or audio file 
3. an associated TEI file with timestamps:
- [x] When I play the video file I should see highlighted text that corresponds to the timestamp in the video. 
- [x] As the video progresses, the highlight should jump when the video reaches the next timestamp/chunk
- [x] The visible text should always be the highlighted text.
- [x] If you click on a timestamped chunk of text or the timestamp in the TEI,
  the video player should jump to that timestamp in the video playback.

**Comment by mark-dce** [comment]
See the OpenVault example here: http://openvault.wgbh.org/catalog/vietnam-1a3f8e-interview-with-madame-ngo-dinh-nhu-1982

**Comment by jcoyne** [comment]
Fixed by 570fe7a
