### ISSUE TITLE
Release Candidate

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#210]
Build a release candidate with dependencies on published versions of all gems.

**Comment by mark-dce** [comment]
Update the following gem file dependencies and then tag a release candidate

resque-web pin to current commit of resque/resque-web
riff - 0.2.0
curation_concerns 0.3.0

**Comment by mark-dce** [comment]
Mimic the pattern for RC1 (https://github.com/curationexperts/goldenseal/releases) and issue a new RC2 release when ready

**Comment by acozine** [comment]
RC2 is out: https://github.com/curationexperts/goldenseal/releases/tag/1.0-rc2
