### ISSUE TITLE
Importer: read identifier from xml:id

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#212]
Use the xml:id provided in the root `<TEI>` node of the document as the 'identifier' attribute.

**EXAMPLES**
Lewald

```
<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="lew1871.0001.002">
```

America's war on poverty

```
<TEI xml:id="avi14885.00654.023">
```

_NOTE:_ we'll recommend to WUSTL that they change ccr records to match the other collections.
Circuit Court

```
<teiCorpus xmlns="http://www.tei-c.org/ns/1.0" xml:id="ccr1815.00757.018"> 
```

**Comment by val99erie** [comment]
@mark-dce If we switch to using the xml:id for the identifier, then we might lose some data.  For example, in the case of the Frank Addonizio interview, there are 2 identifiers:
'add14885.01250.032' and 'MAVIS Interview Record: 1250', so we would lose that second identifier.

How do you want to handle it?  Some options:
1. Have the importer check for both xml:id and tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:idno nodes.
2. Ask WUSTL team to update their TEI files to always have the "idno" node.
3. Just use xml:id and lose the additional identifiers

**Comment by mark-dce** [comment]
@val99erie we're not really "losing" the information any more than we're "losing" a bunch of other metadata in the TEI that we're not choosing to import right now.  The source TEI document is still attached to the work, so anyone who really needs the MAVIS ID still has access to it.

Looking at the other collections, it looks like all the samples have an xml:id.  Outside of the Interviews, I don't see anything else with a Mavis Interview Record.

We just need something unique to identify already imported records, so let's go with the id we're seeing on every xml document (xml:id) instead of the one that's unique to the interview samples.

If it's not hard and it doesn't break the importer, I like your option 1 - just import the MAVIS ID as well and have two identifiers associated with the work - that's not unusual for items that have to be cross-references to multiple systems.  

If there's some reason that Option 1 ends up not being workable, let's just go with Option 3.
