### ISSUE TITLE
Text works not displaying images

### ISSUE THREAD

**Issue by acozine** [curationexperts/goldenseal#223]
On the sandbox, this text work
http://wustl.curationexperts.com/concern/texts/j3860762v
has attached image files for its pages. If I click on an image file in the list of files, the image looks good:
http://wustl.curationexperts.com/concern/file_sets/4b29b6520
but in the main display page for the text work, the images do not show up in the Images and Text viewer.
If I open the Images Only viewer, I see a gray bar at the top of each page, but no image.

**Comment by jcoyne** [comment]
```
t = Text.find('sb397862w')
t.id_for_filename('gesc_01_0006_005.tif')
=> nil
fs = FileSet.find('4t64gn51s')
fs.to_solr.fetch('label_ssi')
=> "gesc_01_0006_005.tif"

```

It looks like this is because generic_work_ids is no longer indexed on FileSet
