### ISSUE TITLE
Hide "Select an Action" if user doesn't have any rights

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#225]
If I'm not logged in and I click on "Select an Action" in search results under an Administrative Collection, I get a weird skinny box with nothing in it.
- [x] Suppress the button entirely if the user isn't logged in
- [x] Suppress the button on Admin Collections if the user isn't an Administrator

<img width="749" alt="wustl 225 - select an action for admin collections" src="https://cloud.githubusercontent.com/assets/3064318/10884351/40666a1c-813d-11e5-9d0f-86fcdd486dd0.png">

<img width="734" alt="wustl 225 - select an action for works - not logged in" src="https://cloud.githubusercontent.com/assets/3064318/10884352/406b9820-813d-11e5-9695-e82d4764b6a6.png">

**Comment by jcoyne** [comment]
Fixed by f2f3a73e4bba1080afa5109faddddc5bb8040332
