### ISSUE TITLE
Unable to set thumbnail/representative for a Collection

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#234]
1. Create a personal collection
2. Add an image to the collection
3. Edit the collection, and select the image as the thumbnail and representative
4. Save the form
5. Notice that the representative doesn't appear on the collection's show page
6. In the rails console, if you find the collection, the representative_id and thumbnail_id are still nil

**Comment by val99erie** [comment]
Hint:  I think the problem is that this view is trying to load a FileSet, but the representative of the collection is an Image.
https://github.com/curationexperts/goldenseal/blob/master/app/views/curation_concerns/base/_representative_media.html.erb#L1

We may need to write a separate view partial for the representative of a collection, instead of using the base:
https://github.com/projecthydra-labs/curation_concerns/blob/master/app/views/collections/show.html.erb#L5

**Comment by mark-dce** [comment]
Close #228 if this gets fixed - or close this and remove the representative selection per #228
