### ISSUE TITLE
Deleting Text works fails

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#239]
**STEPS TO REPRODUCE**
1. Ingest a text work (or create one that has > 10 pages)
2. Delete the text work
3. Watch what happens

**Comment by jcoyne** [comment]
Are you seeing this error?

```
NoMethodError in CurationConcerns::AudiosController#destroy
undefined method `mime_type' for nil:NilClass
```

**Comment by mark-dce** [comment]
Testing on http://wustl.curationexperts.com/concern/texts/7h149q42b 

I get a really long delay and then "We're sorry but something went wrong" message in the client

Testing again on http://wustl.curationexperts.com/concern/texts/5m60qs44g
Same results - "something went wrong"
Production Log gist: https://gist.github.com/mark-dce/51d34911315c2c04e04d
