### ISSUE TITLE
C-2: Metadata fields for Image show page

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#31]
Display metadata field on the show page for an Image.

> Customize the layout and metadata fields shown for images.  Configure the OpenSeadragon based, IIIF-compliant image viewer to WU specific requirements.

**Comment by val99erie** [comment]
Questions:
- [x] Which metadata fields should be displayed on the show page for an Image object?

**Comment by mark-dce** [comment]
- [x] Show original image dimensions from technical metadata
- [x] Show original image file / mime-type from technical metadata

**Comment by jcoyne** [comment]
Are we talking about an Image work or an attached file?

**Comment by mark-dce** [comment]
the representative work - i.e. I have an image work, it has a primary (representative) image.  I want to show that image's dimensions along with all the other descriptive metadata for the work.
