### ISSUE TITLE
Configure apache to use x-sendfile

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#34]
- [x] install x-sendfile on wustl.curationexperts.com
- [x] create ansible role for installing and configure xsendfile on centos
- [x] apply ansible role to wulib.wustl.edu servers

**Comment by acozine** [comment]
Our sandbox is configured and ready for testing.

**Comment by acozine** [comment]
I installed from source on our sandbox - there is a package version in the epel repo - mod_xsendfile. Try that in Ansible instead of building from source.

**Comment by mark-dce** [comment]
@acozine - video files no longer play back and we think it may be related to how apache handles media downloads.  Can you see whether the cat video will play for you? http://wustl.curationexperts.com/concern/videos/z316q156s

If not, can you try undoing your changes and see if the video plays back without them?

**Comment by jcoyne** [comment]
@acozine nevermind marks request

**Comment by acozine** [comment]
Ansible update pushed. I emailed Mark at WUSTL with the details of the upgrade. I also suggested that they try building from scratch with ansible after we figure out the FITS dependency issue.
