### ISSUE TITLE
G-1	Bulk ingest support - TEI content

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#37]
jpeg2000 and TEI here:
`/opt/sample-data/DCE_WU_content_model/circuit-court-records-TEI-textimage`

**Comment by val99erie** [comment]
Question:
- [x] Which collection/works are we using as the primary test for the importer?  We have sample data for one of the Fanny Lewald novels; is that the one we should test against?

**Comment by mark-dce** [comment]
We should develop against the Fanny Lewald collection - corrected TEI and valid (receded) jp2s are at `/opt/sample-data/fanny-lewald-TEI-textimage-DCE-changes`

**Comment by mark-dce** [comment]
> *_Provide command line import for single file and directory-level ingest of TEI content. *_ ~~Configure appropriate metadata and full-text indexing.~~

**Comment by mark-dce** [comment]
> **Provide command line import for single file and directory-level ingest of TEI content.** ~~Configure appropriate metadata and full-text indexing. (separate story)~~

Using the Lewald Collection at /opt/sample-data/fanny-lewald-TEI-textimage-DCE-changes, write a batch importer that will 
- [x] scan a supplied directory for valid TEI files, 
- [x] Create a new Text work for each TEI file found,
- [x] Give it a title from the `<fileDesc><titleStmt><title>` node in the tei-xml file
- [x] Scan each TEI work found for references to image files
- [x] Search for matching files in the directory
- [x] Import each file found as a generic work attached to the main work

**Comment by val99erie** [comment]
@mark-dce How should the importer behave if it finds that a record already exists?  Should it delete the existing record and re-import?  Or should it skip that record and print a skip/error message?

**Comment by mark-dce** [comment]
If there's already a work with the same ID, just print out a message "A work with #{ID} already exists, file #{filename} with the same ID will be skipped.  If you really want to import the file, please delete the existing work with that ID first."
