### ISSUE TITLE
G-2: Import VRA and images

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#38]
The behavior of the importer should be similar to the TEI and Transcript importer.
- [x] The importer should take the path to a directory containing one or more TEI transcripts,  
- [x] The importer should take an optional parameter to set the access level [open, institution, private]
- [x] The importer should take an optional parameter to set the Administrative Collection
- [x] The importer should search for associated image files in the directory where the transcript is and it's children

Import the following fields
- [x] **title** /vra/collection/work/image/titleSet/title
- [x] **contributor** /vra/collection/sourceSet/source/name 
- [x] **description** /vra/collection/work/image/relationSet/display
- [x] **content license** /vra/collection/rightsSet/rights/@type
  "publicDomain" maps to "Public Domain Mark 1.0", all others map to "All Rights Reserved"
- [x] **publisher** /vra/collection/locationSet/location/name/@type=other  
- [x] **date_created** /vra/collection/work/image/dateSet  
- [x] **extent** /vra/collection/work/image/measurementsSet

The name of the corresponding image file is at 
- [x] /vra/collection/work/image/titleSet/title/@href

Sample data is located in `/opt/sample-data/DCE_WU_content_model/schiele-VRA-imageonly`

_NOTE:_ Image importer is a prototype,time-bounded feature to help us scope how much additional work would be required to build a complete metadata parser and/or how metadata would need to be modified to be more easily machine readable.

**Comment by val99erie** [comment]
This story is finished, but I haven't been able to test the full import on the sandbox because the sandbox is being used for performance testing today.
