### ISSUE TITLE
A-1	Configuration Management & Build Automation Scripts

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#4]
DCE provides Ansible scripting to support automated configuration management of core infrastructure components including Fedora, SQL database server, Web application server, Solr and related components.
- [x] #1 DCE Sandbox
- [x] #2 WU Sandbox
- [x] #3 WU Production

**Comment by acozine** [comment]
ffmpeg install tested on AWS - installation works.

**Comment by acozine** [comment]
hydrademo.wulib.wustl.edu
hydraqa.wulib.wustl.edu
hydraprod.wulib.wustl.edu
all created with ansible - hydraprod is open to the world; the other servers may be internal-only
