### ISSUE TITLE
G: Set visibility for bulk import

### ISSUE THREAD

**Issue by val99erie** [curationexperts/goldenseal#44]
By default when you create a work, if you don't explicitly set the visibility, it will be set to the most restricted level.  The current behavior of the importer is to not set visibility, so all bulk imported works will have the default visibility.  It would be labor-intensive to edit each new record to change the visibility, so we'll probably need a way to set the visibility for multiple records at a time.

Some possible options:
- Add a command line switch to the importer script so that the person who is running the import can set the visibility for all objects in that import.
- Some kind of multi-select batch edit in the UI.
- Ability to change the visibility at the collection level and have the new visibility apply to the members of the collection.
- A command line script or rake task to edit visibility for multiple records.

**Comment by mark-dce** [comment]
Let's do one of the two command line options (importer switch or separate task to set visibility on multiple records).  Whichever is easier.
