### ISSUE TITLE
Send curation_concern derivative defaults to WU

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#46]
Send the default derivative specs for 
- [ ] audio
- [x] video
- [ ] images

**Comment by jcoyne** [comment]
For mp4 -s 320x240 -vcodec mpeg4 -acodec aac -strict -2 -g 30 -b:v 345k -ac 2 -ab 96k -ar 44100

for webm -s 320x240 -vcodec libvpx -acodec libvorbis -g 30 -b:v 345k -ac 2 -ab 96k -ar 44100

**Comment by mark-dce** [comment]
Closing this since we're just using hydra-derivatives defaults.  If WU has a specific need for other settings, we'll add that to a future phase of work.
