### ISSUE TITLE
B-2	Core metadata modeling 

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#49]
From the SOW:

> DCE will implement a core profile of Dublin Core metadata terms to support repository-wide search, browse, and administrative activities.  Core terms will be determined based on TEI, MODS, VRA, and other metadata cross-walks provided by WU.  The system will provide RDF based metadata to support future linked open data (LOD) interfaces (including DPLA harvesting). The system will support supplemental schemas via attached metadata files.

**Comment by mark-dce** [comment]
I think this requirement is satisfied by [CurationConcerns::BasicMetadata](https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/basic_metadata.rb)

**Comment by val99erie** [comment]
See #41 for dc:date field
