### ISSUE TITLE
Video thumbnail not working

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#63]
When I create a new audio or video work, the file I upload in the 'new' form should be used as the representative example.

**Comment by mark-dce** [comment]
This should actually be the case for most works - images, audio, video, & documents.  (I'm not quite sure what the derivative for TEI text should be or how it should work).  When this is closed, check to see if it also fixes #76 - I'm not sure if it's related or a separate issue.

**Comment by val99erie** [comment]
After talking with Mark, here's the problem that this ticket is trying to address.

When you create a new Video:

> There should be a thumbnail of the first frame under the word "File" instead of a broken link with the word Thumbnail

**Comment by val99erie** [comment]
Currently, when you create a video, the representative gets set to the GenericFile that you uploaded.  I'm not sure what happens when the characterization job runs.  It sounds like it should create a thumbnail and then set the representative to that.  I'll take a look and see if that's the problem.

**Comment by val99erie** [comment]
This seems to have gotten fixed in this commit:
https://github.com/projecthydra-labs/curation_concerns/commit/ec2aa6179bd477b6e7902366360346603bf991c2
