### ISSUE TITLE
Remove "A PDF is preferred"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#67]
**ROUTE**
/concern/container/ID/generic_files/new
<img width="581" alt="wustl 067 - generic file remove pdf reference" src="https://cloud.githubusercontent.com/assets/3064318/9531255/a319a964-4cca-11e5-8790-c65a681c725a.png">

**ROUTE**
/concern/documents/new 
(change for all work types)
<img width="497" alt="wustl 067 - new document remove pdf reference" src="https://cloud.githubusercontent.com/assets/3064318/9531259/ac92928a-4cca-11e5-83cf-6790295ee6ae.png">

**Comment by jcoyne** [comment]
https://github.com/projecthydra-labs/curation_concerns/issues/255
