### ISSUE TITLE
Thumbnails not being generated for Documents

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#68]
**EXAMPLES**
Document: http://wustl.curationexperts.com/concern/documents/6t053f984
Spreadsheet: http://wustl.curationexperts.com/concern/documents/vx021f082
Presentation: http://wustl.curationexperts.com/concern/documents/cj82k728n

**Comment by jcoyne** [comment]
Has this been tested since #65 was completed?

**Comment by mark-dce** [comment]
Yes

**Comment by jcoyne** [comment]
Okay, maybe this is due to https://github.com/projecthydra/hydra-derivatives/issues/77

**Comment by jcoyne** [comment]
I tested:

```
$ soffice --invisible --headless --convert-to jpg --outdir /tmp install/fits-0.8.4/tools/exiftool/perl/t/images/PDF.pdf
/usr/lib64/libreoffice/program/soffice.bin X11 error: Can't open display:
   Set DISPLAY environment variable, use -display option
   or check permissions of your X-Server            1:31
jcoyne       soffice --version
LibreOffice 4.2.6.3 420(Build:3)
```

**Comment by jcoyne** [comment]
Another developer says it works on LibreOffice 4.2.8.2 420m0(Build:2)

**Comment by jcoyne** [comment]
I found this documentation:

> If you receive the error "X11 error: Can't open display:" when running the above command, then you may need to install the "headless" OpenOffice.org package from your Linux distribution. On Ubuntu/Debian, this package is called openoffice.org-headless. 

https://wiki.alfresco.com/wiki/Running_OpenOffice_From_Terminal

**Comment by mark-dce** [comment]
Also listed in hydra-derivatives here: https://github.com/projecthydra/hydra-derivatives#dependencies

**Comment by acozine** [comment]
Installed the headless library on our sandbox `sudo yum install libreoffice-headless` and Justin's test above worked:

```
[alicia@ip-10-157-125-185 opt]$ soffice --invisible --headless --convert-to jpg --outdir /tmp install/fits-0.8.4/tools/exiftool/perl/t/images/PDF.pdf
convert /opt/install/fits-0.8.4/tools/exiftool/perl/t/images/PDF.pdf -> /tmp/PDF.jpg using draw_jpg_Export
```
