### ISSUE TITLE
Display rights label instead of URI in search results

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#69]
Search result listings should display Rights as the label instead of the URI for the selected licensing.
<img width="579" alt="wustl 068 - right label instead of uri" src="https://cloud.githubusercontent.com/assets/3064318/9531491/b8d19d7e-4ccb-11e5-843d-42d85ddb050e.png">

**Comment by jcoyne** [comment]
we should probably index `rights_label_ss` and display that.

**Comment by mark-dce** [comment]
Why does "all rights reserved" already show up as a string:
<img width="958" alt="wustl 069 - content license strings" src="https://cloud.githubusercontent.com/assets/3064318/9666821/00e0a28c-523e-11e5-854e-cc26891d13fe.png">

**Comment by jcoyne** [comment]
@mark-dce because it doesn't have a uri

**Comment by mark-dce** [comment]
@jcoyne sorry - I figured we were using the same URI for all rights reserved as in ADRL:
http://www.europeana.eu/portal/rights/rr-r.html
Is there a reason we wouldn't want to propose using this as the URI?

**Comment by jcoyne** [comment]
We should use that. This code comes from sufia which predates the work of compiling the predicates
