### ISSUE TITLE
"Your Institution" as access rights gives "something went wrong"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#70]
**STEPS TO REPRODUCE**
1. Log in to the application
2. Click the + (Add a Work) button and select any work type
3. Give your work a title
4. Under **Access Rights** select **Your Institution**

**Expected Results**
A new work with no attachments

**Actual Results**
We're sorry, but something went wrong.

**Comment by jcoyne** [comment]
Due to https://github.com/projecthydra-labs/curation_concerns/issues/239
