### ISSUE TITLE
Video derivatives not playing

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#71]
MPEG-1 http://wustl.curationexperts.com/concern/videos/dn39x152w
WEBM http://wustl.curationexperts.com/concern/videos/kp78gg36g

**Comment by mark-dce** [comment]
Various encapsulation and codec samples are on the demo server:

```
[deploy@ip-10-157-125-185 ~]$ cd /opt/sample-data/
[deploy@ip-10-157-125-185 sample-data]$ ls -la BLACK*
-rw-r--r--. 1 deploy deploy 1231752 Aug 27 21:33 BLACKandWHITE_countdown_leader.avi
-rw-r--r--. 1 deploy deploy 2574188 Aug 27 21:33 BLACKandWHITE_countdown_leader.m4v
-rw-r--r--. 1 deploy deploy 3124865 Aug 27 21:33 BLACKandWHITE_countdown_leader.mov
-rw-r--r--. 1 deploy deploy 1366196 Aug 27 21:33 BLACKandWHITE_countdown_leader.mp2.ts
-rw-r--r--. 1 deploy deploy 4438020 Aug 27 21:33 BLACKandWHITE_countdown_leader.mpg
-rw-r--r--. 1 deploy deploy  859078 Aug 27 21:33 BLACKandWHITE_countdown_leader.ogg
-rw-r--r--. 1 deploy deploy 1844159 Aug 27 21:33 BLACKandWHITE_countdown_leader.webm
```

**Comment by jcoyne** [comment]
I think this is now working (see https://github.com/projecthydra-labs/curation_concerns/pull/221). @mark-dce please retest.

**Comment by mark-dce** [comment]
MP4: Still no playback in Safari or Chrome using BLACKandWHITE_countdown_leader.m4v - no derivative appears and clicking the playback arrow has no effect.
Sample work is here: http://wustl.curationexperts.com/concern/videos/bz60cw24r

MPEG-1: Using BLACKandWHITE_countdown_leader.mpg now gives first frame derivative and the player displays the full video.  Hitting the playback arrow still has no effect.  Moving the scrubber displays the correct frame of the video.
Sample work is here: http://wustl.curationexperts.com/concern/videos/sq87bt605

**Comment by jcoyne** [comment]
http://wustl.curationexperts.com/concern/videos/bz60cw24r is broken because the derivative doesn't exist (404): http://wustl.curationexperts.com/downloads/fj236208t?file=webm

**Comment by mark-dce** [comment]
Uploaded a new MP4 as http://wustl.curationexperts.com/concern/videos/nz805z690

Playback in Chrome work, but scrubber does not work
Scrubber in Safari works, but playback does not work

**Comment by jcoyne** [comment]
Seems to work okay in Firefox.  On my Chrome the scrubber seems to work for the buffered portion, but not forward of that.  Is that what you see?

**Comment by jcoyne** [comment]
When I send:
`curl 'http://wustl.curationexperts.com/downloads/0p0966881?file=webm'`

Rails thinks it's sent okay.

```
I, [2015-08-28T20:06:20.283758 #10332]  INFO -- : Sent file /opt/goldenseal/derivatives/0p0966881/webm.webm (0.1ms)
```

And the file exists:

```
$ ls -la /opt/goldenseal/derivatives/0p0966881/webm.webm
-rw-rw-r--. 1 deploy deploy 376968 Aug 28 17:09 /opt/goldenseal/derivatives/0p0966881/webm.webm
```

But the web server returns: 

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /downloads/0p0966881 was not found on this server.</p>
</body></html>
```

Is it possible that MOD_XSENDFILE is misconfigured?

**Comment by jcoyne** [comment]
Confirmed. Error in the apache log:

```
[Fri Aug 28 20:10:53.976565 2015] [:error] [pid 936] (20023)The given path was above the root path: [client 67.220.14.148:52525] xsendfile: unable to find file: /opt/goldenseal/derivatives/0p0966881/webm.webm
```

**Comment by jcoyne** [comment]
In /etc/httpd/conf.d/goldenseal.conf

Changed
XSendFilePath /opt/xsendfile

to

XSendFilePath /opt/goldenseal/derivatives

**Comment by jcoyne** [comment]
Okay @mark-dce, working now?

**Comment by acozine** [comment]
I updated the Ansible scripts to use /opt/{{ project_name }}/derivatives for the XSendFilePath.

**Comment by mark-dce** [comment]
- [x] MPEG-1 http://wustl.curationexperts.com/concern/videos/b2773v70j
- [ ] MPEG-2 http://wustl.curationexperts.com/concern/videos/b8515n36q - no playback derivative being generated
- [x] MPEG-4 http://wustl.curationexperts.com/concern/videos/cz30ps66x
- [x] MOV http://wustl.curationexperts.com/concern/videos/sx61dm28w
- [ ] WEBM http://wustl.curationexperts.com/concern/videos/f7623c581 - only displays "loading" message in player

_NOTE:_ I can download the file attachment to each of the works above and play it successfully in a desktop player (e.g. VLC)

**Comment by jcoyne** [comment]
The m4v file you uploaded is not an MPEG4, and FITS returns a conflict, thus it doesn't know it's a video:  

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.6.2" timestamp="8/31/15 8:39 PM">
  <identification status="CONFLICT">
    <identity format="ISO Media, MPEG v4 system, version 1" mimetype="video/mp4" toolname="FITS" toolversion="0.6.2">
      <tool toolname="file utility" toolversion="5.11"/>
    </identity>
    <identity format="ISO Media, MPEG v4 system, version 2" mimetype="video/mp4" toolname="FITS" toolversion="0.6.2">
      <tool toolname="Exiftool" toolversion="9.06"/>
    </identity>
  </identification>
  <fileinfo>
    <lastmodified toolname="Exiftool" toolversion="9.06" status="SINGLE_RESULT">2015:08:31 20:38:59+00:00</lastmodified>
    <created toolname="Exiftool" toolversion="9.06" status="SINGLE_RESULT">2015:08:27 20:40:47</created>
    <filepath toolname="OIS File Information" toolversion="0.1" status="SINGLE_RESULT">/tmp/BLACKandWHITE_countdown_leader.m4v20150831-2860-12t15vi.m4v</filepath>
    <filename toolname="OIS File Information" toolversion="0.1" status="SINGLE_RESULT">BLACKandWHITE_countdown_leader.m4v</filename>
    <size toolname="OIS File Information" toolversion="0.1" status="SINGLE_RESULT">2574188</size>
    <md5checksum toolname="OIS File Information" toolversion="0.1" status="SINGLE_RESULT">14ff49747d9af77588f1da66c982623c</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.1" status="SINGLE_RESULT">1441053539000</fslastmodified>
  </fileinfo>
  <filestatus/>
  <metadata/>
</fits>
```

**Comment by mark-dce** [comment]
I made a true mp4 (by converting the source mpeg-1 file using ffmpeg) and it works correctly.
