### ISSUE TITLE
Audio Playback Issues

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#72]
- [ ] Scrubber doesn't appear in Safari
- [ ] Scrubber doesn't move in Chrome
- [ ] Can't replay audio without reloading page

Feel free to break these out into separate issues if they're not actually related.

**Comment by jcoyne** [comment]
I think this is now working (see https://github.com/projecthydra-labs/curation_concerns/pull/221). @mark-dce please retest.

**Comment by mark-dce** [comment]
Ok, it's different, or I'm more patient... but it still doesn't really work

_In Safari_
1. When I load the page, I get the player with a "Loading" message
2. After a few moments, the "Loading" message changes to "Live Playback" and I can click the play button to start playback
3. When I click the playback button, I continue to get the "Live Playback" message with no scrubber
4. Once the playback finishes, if I hit playback again, the the playback arrow momentarily changes to the pause icon, and then quickly changes back to the playback arrow with nothing having played and I still have the "Live Playback" message instead of a scrubber.
5. If I keep clicking on the playback button (usually 1-3 times), I finally get playback with a scrubber instead of the "Live Playback" message and I can scrub back and forth through the audio.  (It would probably be nice to give this a little more width since the scrub control is really short right now).
6. In this final state, the playback controller displays the time remaining as "infinity:NaN" instead of the actual time remaining...

_In Chrome_
1. When I load the page, I get the player with a scrubber and no playback time info.
2. After a brief pause, the scrubber displays the actual length of the clip and I can start playback
3. During playback, the scrubber moves to represent the approximate playback position.
4. After playback, I can hit the play button again and playback begins from the start of the clip
5. I _can not_ use the scrubber to change the playback location, after clicking or moving it, it just jumps back to it's previous position.

**Comment by mark-dce** [comment]
FWIW - I get basically the same behavior with MP3 and WAV audio except that MP3 display the correct time remaining (instead of NaN) on replays.

The samples I used are available on the wustl demo server:

```
/opt/sample-data
$ ls -la 20*
-rw-r--r--. 1 deploy deploy  803610 Aug 28 15:31 20 seconds.mp3
-rw-r--r--. 1 deploy deploy 3527976 Aug 28 15:32 20 seconds.wav
```

WAV: http://wustl.curationexperts.com/concern/audios/w37636771
MP3: http://wustl.curationexperts.com/concern/audios/xg94hp52v

**Comment by jcoyne** [comment]
Looks like we might need to send the duration headers too: http://stackoverflow.com/a/19413030/162852

**Comment by jcoyne** [comment]
How about now?

**Comment by mark-dce** [comment]
- [x] The scrubber appears in Safari, Chrome, & Firefox
- [x] The scrubber moves with playback
- [x] I can use the scrubber to change the playback location
- [x] I can replay the audio without reloading the page
