### ISSUE TITLE
OGG encoded video files crash system

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#73]
Attempting to create a new video with 
/opt/sample-data/BLACKandWHITE_countdown_leader.ogg

gives a "something went wrong error" with errors in the fedora log.

**Comment by jcoyne** [comment]
https://github.com/fcrepo4/fcrepo4/issues/893

We can downgrade fedora to 4.2.0 and that will probably make this go away.

**Comment by jcoyne** [comment]
It appears this will be fixed in Fedora 4.3.1 https://jira.duraspace.org/browse/FCREPO-1712

**Comment by jcoyne** [comment]
Should be fixed now.
