### ISSUE TITLE
Thumbnails in the files list for a work should be a consistent size (width)

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#75]
The current document thumbnails (.doc, .xls, .ppt, .pdf) produce thumbnails that are displaying  pretty large:

_CURRENT_
PDF: 329x493
DOC: 816x1056
PPT: 920x720
XLS: 816x1056

**ACCEPTANCE**
- [x] All documents have the same size maximum bounding square for thumbnails
- [x] The bounding square is the same as for images

**Comment by jcoyne** [comment]
Is this fixed now?

**Comment by mark-dce** [comment]
They all have the same width which is good enough
