### ISSUE TITLE
Use icon as thumbnail for audio files

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#78]
For places where we would normally show a thumbnail representation of a work, use an audio Icon for audio files.

Possible options:
http://case.curationexperts.com/assets/Audio-12285bf467bdd0e1b547f61afcc05ce1.png

glyphicons-volume-up

glyphicons-voice

glyphicons-voicemail

_or anything similar_

**Comment by jcoyne** [comment]
Code for that is here: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/helpers/curation_concerns/thumbnail_helper.rb#L3-L9

**Comment by jcoyne** [comment]
glyphicons-voice and glyphicons-voicemail are not valid choices unless you buy a full license to glyphicons, they are not in glyphicons halflings set.
