### ISSUE TITLE
Use consistent terminology for ::RDF::DC.description

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#79]
In the show view, it's called "Abstract"; in the edit view, it's called "Description".

**ACCEPTANCE**
- [ ] Use "Description" as the label for ::RDF::DC.description in show, edit, and index views

**CURRENT INDEX VIEW**
<img width="578" alt="wustl 079 - description label - index view" src="https://cloud.githubusercontent.com/assets/3064318/9585454/aec098a8-4fdc-11e5-80fe-0abbbaa405fd.png">

**CURRENT SHOW VIEW**
<img width="912" alt="wustl 079 - description label - show view" src="https://cloud.githubusercontent.com/assets/3064318/9585474/dcef37ca-4fdc-11e5-9cf8-e0cb8ea8feee.png">

**CURRENT EDIT VIEW**
<img width="576" alt="wustl 079 - description label - edit view" src="https://cloud.githubusercontent.com/assets/3064318/9585481/e5fde398-4fdc-11e5-9066-7870459cfdd9.png">

**Comment by jcoyne** [comment]
Fixed by 5f7394d
