### ISSUE TITLE
Change "Rights" to "Content License" in search index view

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#81]
Edit and Show views use the word "Rights" for machine enforced access rights, so use "Content License" consistently to avoid confusion.

**Comment by val99erie** [comment]
Waiting for a PR to be resolved in the curation_concerns gem:
https://github.com/projecthydra-labs/curation_concerns/pull/242

**Comment by jcoyne** [comment]
@val99erie I've pinned goldenseal to that PR, so unblocked.
