### ISSUE TITLE
Always show facets in desktop view

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#82]
The functionality of the "Limit your search" checkbox isn't total intuitive and it's barely visible in firefox.  Can we just get rid of it and show the facets at all times?  Is there some benefit to hiding facets?

<img width="596" alt="wustl 082 - limit your search checkbox" src="https://cloud.githubusercontent.com/assets/3064318/9589472/39f51f40-4ff4-11e5-9735-473d93552e71.png">

**Comment by jcoyne** [comment]
That is a button that allows facets to be shown/hidden on a mobile browser. It's not supposed to show at all on desktop resolutions.

**Comment by mark-dce** [comment]
Ok, so this ticket should be about making the desktop view work:

**ACCEPTANCE**
- [ ] When I view collections, works, or search results on a device with display larger than a tablet, I should always see the facet list as an option

For mobile devices, see #85

**Comment by jcoyne** [comment]
Fixed by 42d606532e42d2cc542d9e6ed3f75c4a101d3a7e
