### ISSUE TITLE
Sort by date uploaded doesn't work

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#84]
I just uploaded 5 new files.  When I sort by date uploaded descending, they show up as items 13-17 out of 40 - they should be items 1-5.  When I sort by date uploaded ascending, they show up as items 36-40 out of 40 as expected.

<img width="524" alt="wustl 084 - sort by date uploaded - ascending" src="https://cloud.githubusercontent.com/assets/3064318/9590046/e6f60490-4ff7-11e5-9219-b12bd2938c26.png">

<img width="511" alt="wustl 084 - sort by date uploaded - descending" src="https://cloud.githubusercontent.com/assets/3064318/9590045/e6f4de44-4ff7-11e5-92cc-364f042f8fbb.png">

**Comment by mark-dce** [comment]
The same problem appears to be occurring for "date modified" sorts.  Ascending appears to be working correctly; descending is not ordering items correctly.

**Comment by val99erie** [comment]
@mark-dce  Sort by date uploaded and modified is working -- it sorts by date, but not by time.  If you want those sorts to take time into consideration, I can change it to use the `system_create` and `system_modified` instead.

**Comment by val99erie** [comment]
After discussion:  let's change it to time sort instead of date sort

**Comment by val99erie** [comment]
After more discussion, we decided it's probably better to change the curation_concerns gem so that those fields are DateTime instead of Date.
