### ISSUE TITLE
Empty field in select representive dropdown.

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#90]
<img width="420" alt="screen shot 2015-09-01 at 2 25 51 pm" src="https://cloud.githubusercontent.com/assets/92044/9614176/b9fef640-50b5-11e5-81c3-0e82ccd79eee.png">

On this page:
http://wustl.curationexperts.com/concern/texts/rf55z7692/edit

**Comment by val99erie** [comment]
Investigate why there is an empty slot.  If it's truly empty, take it out of the list.  If it's something where the label isn't displaying properly, fix the label.

**Comment by jcoyne** [comment]
Looks like this will be fixed by https://github.com/projecthydra-labs/curation_concerns/pull/277.  Waiting until that gets wrapped up.
